import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        // Status / semantic
        "status-info": "#2167F5",
        "status-success": "#58B388",
        "status-warning": "#F8C540",
        // Brand / interactive
        primary: "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#0b1940",
        "on-primary-container": "#7682af",
        "primary-fixed": "#dce1ff",
        "primary-fixed-dim": "#b9c5f5",
        "on-primary-fixed": "#0b1940",
        "on-primary-fixed-variant": "#39456e",
        "inverse-primary": "#b9c5f5",
        secondary: "#3074CA",
        "on-secondary": "#ffffff",
        "secondary-container": "#67a4fe",
        "on-secondary-container": "#003972",
        "secondary-fixed": "#d5e3ff",
        "secondary-fixed-dim": "#a8c8ff",
        "on-secondary-fixed": "#001b3c",
        "on-secondary-fixed-variant": "#00468a",
        // Surface
        background: "#f8f9fa",
        surface: "#f8f9fa",
        "surface-bright": "#f8f9fa",
        "surface-dim": "#d9dadb",
        "surface-tint": "#515d87",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "surface-container": "#edeeef",
        "surface-container-high": "#e7e8e9",
        "surface-container-highest": "#e1e3e4",
        "surface-variant": "#e1e3e4",
        "inverse-surface": "#2e3132",
        "inverse-on-surface": "#f0f1f2",
        // Content
        "on-surface": "#191c1d",
        "on-surface-variant": "#45464e",
        "on-background": "#191c1d",
        outline: "#76767f",
        "outline-variant": "#c6c6cf",
        // Tertiary
        tertiary: "#000000",
        "tertiary-container": "#20005e",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#8c74d7",
        "tertiary-fixed": "#e8ddff",
        "tertiary-fixed-dim": "#cebdff",
        "on-tertiary-fixed": "#20005e",
        "on-tertiary-fixed-variant": "#4d3495",
        // Error
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        xs: "4px",
        base: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "40px",
        "2xl": "64px",
        "3xl": "80px",
      },
      fontFamily: {
        sans: ["Manrope", "Inter", "sans-serif"],
        display: ["Manrope", "sans-serif"],
        heading: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        display: ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        h1: ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        h2: ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        h3: ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        mono: ["13px", { lineHeight: "1.5", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
